services:

  nginx:
    image: tdt-nginx
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend

  frontend:
    image: tdt-frontend
    build: ./frontend
    environment:
      NEXT_PUBLIC_BACKEND_URL: ${BACKEND_URL:-http://localhost/cms}

  backend:
    image: tdt-backend
    build: ./backend
    depends_on:
      - db
    environment:
      BACKEND_URL: ${BACKEND_URL:-http://localhost/cms}
      APP_KEYS: "mAzXoQi1qI3PzEhF1MNWPA==,dEkYXLPUuSlC26STB0ZyKA=="
      API_TOKEN_SALT: Lniabeo/mh7ynqF/GTfpOw==
      ADMIN_JWT_SECRET: Hr+r0OSOTgUzfce6q9/AvA==
      TRANSFER_TOKEN_SALT: 95PYtBD/vlf9x0fB76N/sw==
      JWT_SECRET: T+8DOhQmklZ+TH7ihClOKg==
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: tdt
      DATABASE_USERNAME: akvo
      DATABASE_PASSWORD: password
      DATABASE_SSL: false
      EMAIL_CONFIRMATION_URL: ${PUBLIC_URL:-http://localhost/verify-email}
      PASSWORD_RESET_URL: ${PUBLIC_URL:-http://localhost/reset-password}
      PLUGIN_PROVIDERS: ${PLUGIN_PROVIDERS:-local}
      SMTP_HOST: ${SMTP_HOST:-}
      SMTP_PORT: ${SMTP_PORT:-}
      SMTP_USERNAME: ${SMTP_USERNAME:-}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-}
      SMTP_FROM: ${SMTP_FROM:-}
      GCS_SERVICE_ACCOUNT: ${GCS_SERVICE_ACCOUNT:-{}}
      GCS_BUCKET_NAME: ${GCS_BUCKET_NAME:-}
      GCS_BASE_PATH: ${GCS_BASE_PATH:-}
      GCS_BASE_URL: ${GCS_BASE_URL:-}
      GCS_PUBLIC_FILES: ${GCS_PUBLIC_FILES:-}
      GCS_UNIFORM: ${GCS_UNIFORM:-}

  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  pgadmin:
    image: dpage/pgadmin4:8
    restart: always
    volumes:
      - ./pgadmin4/servers.json:/pgadmin4/servers.json
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 5050:5050
    depends_on:
      - db
    environment:
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_DEFAULT_EMAIL=dev@akvo.org
      - PGADMIN_DEFAULT_PASSWORD=password

  mailpit:
    image: axllent/mailpit:v1.21
    restart: unless-stopped
    ports:
      - 8025:8025
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  pg-data:
  pgadmin-data:
